baseURL : "https://nilsmagnus.github.io/"
languageCode : "en-us"
title : "Random codewalks"
theme : "contrast"

menu:
  main:
  - {name: "Home", url: "/", identifier: "home", weight: 1}
  - {name: "About", url: "/about/me", identifier: "address-card", weight: 2}
